import "../global.css";
export const metadata = {
  // title: 'Next.js',
  title: {
    absolute: "",
    default: "Next.js Learn-Next.js",
    template: "%s | next.js",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
